#!/usr/bin/env bash
# Nix wrapper script, generated by Nixie (https://github.com/nixie-dev/nixie)
# Nixie (c) Karim Vergnes <me@thesola.io>
# Built using Amber 0.6.0-alpha-nix-32bdcbd (https://amber-lang.com)

[ "$EUID" -ne 0 ] && { { command -v sudo >/dev/null 2>&1 && __sudo=sudo; } || { command -v doas >/dev/null 2>&1 && __sudo=doas; }; }
if [ -n "$ZSH_VERSION" ]; then
    EXEC_SHELL="zsh"
    IFS='.' read -A EXEC_SHELL_VERSION <<< "$ZSH_VERSION"
elif [ -n "$KSH_VERSION" ]; then
    EXEC_SHELL="ksh"
    __exec_shell_version="${.sh.version##*/}"
    IFS='.' read -a EXEC_SHELL_VERSION <<< "${__exec_shell_version%% *}"
else
    EXEC_SHELL="bash"
    EXEC_SHELL_VERSION=("${BASH_VERSINFO[0]}" "${BASH_VERSINFO[1]}" "${BASH_VERSINFO[2]}")
fi
# split(text: Text, delimiter: Text)
split__4_v0() {
    local text_274="${1}"
    local delimiter_275="${2}"
    local result_276=()
    if [ "$([ "_${EXEC_SHELL}" != "_zsh" ]; echo $?)" != 0 ]; then
        IFS="${delimiter_275}" read -rd '' -A result_276 < <(printf %s "$text_274")
        __status=$?
    elif [ "$([ "_${EXEC_SHELL}" != "_ksh" ]; echo $?)" != 0 ]; then
        if [ "$([ "_${delimiter_275}" != "_
" ]; echo $?)" != 0 ]; then
            while read -r -d $'\n'; do result_276+=("$REPLY"); done < <(echo "$text_274")
            __status=$?
        else
            IFS="${delimiter_275}" read -rd '' -a result_276 < <(printf %s "$text_274")
            __status=$?
        fi
    elif [ "$([ "_${EXEC_SHELL}" != "_bash" ]; echo $?)" != 0 ]; then
        IFS="${delimiter_275}" read -rd '' -a result_276 < <(printf %s "$text_274")
        __status=$?
    fi
    ret_split4_v0=("${result_276[@]}")
    return 0
}

# split_lines(text: Text)
split_lines__5_v0() {
    local text_2816="${1}"
    split__4_v0 "${text_2816}" "
"
    ret_split_lines5_v0=("${ret_split4_v0[@]}")
    return 0
}

# join(list: [Text], delimiter: Text)
join__7_v0() {
    local list_282=("${!1}")
    local delimiter_283="${2}"
    local command_1
    command_1="$(IFS="${delimiter_283}" ; printf "%s
" "${list_282[*]}")"
    __status=$?
    ret_join7_v0="${command_1}"
    return 0
}

# parse_int(text: Text)
parse_int__13_v0() {
    local text_2754="${1}"
    [ -n "${text_2754}" ] && [ "${text_2754}" -eq "${text_2754}" ] 2>/dev/null
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_parse_int13_v0=''
        return "${__status}"
    fi
    ret_parse_int13_v0="${text_2754}"
    return 0
}

# text_contains(source: Text, search: Text)
text_contains__16_v0() {
    local source_15="${1}"
    local search_16="${2}"
    [[ "${source_15}" == *"${search_16}"* ]]
    __status=$?
    ret_text_contains16_v0="$(( __status == 0 ))"
    return 0
}

# starts_with(text: Text, prefix: Text)
starts_with__22_v0() {
    local text_19="${1}"
    local prefix_20="${2}"
    [[ "${text_19}" == "${prefix_20}"* ]]
    __status=$?
    ret_starts_with22_v0="$(( __status == 0 ))"
    return 0
}

# ends_with(text: Text, suffix: Text)
ends_with__23_v0() {
    local text_2843="${1}"
    local suffix_2844="${2}"
    [[ "${text_2843}" == *"${suffix_2844}" ]]
    __status=$?
    ret_ends_with23_v0="$(( __status == 0 ))"
    return 0
}

# slice(text: Text, index: Int, length: Int)
slice__24_v0() {
    local text_259="${1}"
    local index_260="${2}"
    local length_261="${3}"
    local result_262=""
    if [ "$(( length_261 == 0 ))" != 0 ]; then
        local __length_2="${text_259}"
        length_261="$(( ${#__length_2} - index_260 ))"
    fi
    if [ "$(( length_261 <= 0 ))" != 0 ]; then
        ret_slice24_v0="${result_262}"
        return 0
    fi
    result_262="${text_259: ${index_260}: ${length_261}}"
    __status=$?
    ret_slice24_v0="${result_262}"
    return 0
}

# dir_exists(path: Text)
dir_exists__38_v0() {
    local path_265="${1}"
    [ -d "${path_265}" ]
    __status=$?
    ret_dir_exists38_v0="$(( __status == 0 ))"
    return 0
}

# file_exists(path: Text)
file_exists__39_v0() {
    local path_299="${1}"
    [ -f "${path_299}" ]
    __status=$?
    ret_file_exists39_v0="$(( __status == 0 ))"
    return 0
}

# file_write(path: Text, content: Text)
file_write__41_v0() {
    local path_2828="${1}"
    local content_2829="${2}"
    local command_3
    command_3="$(printf '%s
' "${content_2829}" > "${path_2828}")"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_file_write41_v0=''
        return "${__status}"
    fi
    ret_file_write41_v0="${command_3}"
    return 0
}

# dir_create(path: Text)
dir_create__44_v0() {
    local path_264="${1}"
    dir_exists__38_v0 "${path_264}"
    local ret_dir_exists38_v0__87_12="${ret_dir_exists38_v0}"
    if [ "$(( ! ret_dir_exists38_v0__87_12 ))" != 0 ]; then
        mkdir -p "${path_264}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_dir_create44_v0=''
            return "${__status}"
        fi
    fi
}

# array_last(array: [Text])
array_last__71_v0() {
    local array_2748=("${!1}")
    local __length_4=("${array_2748[@]}")
    local index_2749="$(( ${#__length_4[@]} - 1 ))"
    if [ "$(( index_2749 < 0 ))" != 0 ]; then
        ret_array_last71_v0=''
        return 1
    fi
    ret_array_last71_v0="${array_2748[${index_2749}]?"Index out of bounds (at std/array:69:18)"}"
    return 0
}

# array_pop(array: [Text])
array_pop__74_v0() {
    local -n array_278="${1}"
    local __length_5=("${array_278[@]}")
    local length_279="${#__length_5[@]}"
    local index_280="$(( length_279 - 1 ))"
    if [ "$(( index_280 < 0 ))" != 0 ]; then
        ret_array_pop74_v0=''
        return 1
    fi
    local element_281="${array_278[${index_280}]?"Index out of bounds (at std/array:122:27)"}"
    local slice_upper_6="${index_280}"
    local slice_offset_7=0
    local slice_offset_7=$((${slice_offset_7} > 0 ? ${slice_offset_7} : 0))
    local slice_length_8="$(( slice_upper_6 - slice_offset_7 ))"
    local slice_length_8=$((${slice_length_8} > 0 ? ${slice_length_8} : 0))
    array_278=("${array_278[@]:${slice_offset_7}:${slice_length_8}}")
    ret_array_pop74_v0="${element_281}"
    return 0
}

# array_shift(array: [Text])
array_shift__75_v0() {
    local -n array_294="${1}"
    local __length_9=("${array_294[@]}")
    local length_295="${#__length_9[@]}"
    if [ "$(( length_295 == 0 ))" != 0 ]; then
        ret_array_shift75_v0=''
        return 1
    fi
    local element_296="${array_294[0]?"Index out of bounds (at std/array:141:27)"}"
    local slice_upper_10="${length_295}"
    local slice_offset_11=1
    local slice_offset_11=$((${slice_offset_11} > 0 ? ${slice_offset_11} : 0))
    local slice_length_12="$(( slice_upper_10 - slice_offset_11 ))"
    local slice_length_12=$((${slice_length_12} > 0 ? ${slice_length_12} : 0))
    array_294=("${array_294[@]:${slice_offset_11}:${slice_length_12}}")
    ret_array_shift75_v0="${element_296}"
    return 0
}

# env_var_test(name: Text)
env_var_test__117_v0() {
    local name_2746="${1}"
    if [ "$([ "_${EXEC_SHELL}" != "_zsh" ]; echo $?)" != 0 ]; then
        [[ ! -z ${(P)name_2746+z} ]]
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_env_var_test117_v0=0
            return 0
        fi
    elif [ "$([ "_${EXEC_SHELL}" != "_bash" ]; echo $?)" != 0 ]; then
        declare -p -- "${name_2746}" > /dev/null 2> /dev/null
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_env_var_test117_v0=0
            return 0
        fi
    elif [ "$([ "_${EXEC_SHELL}" != "_ksh" ]; echo $?)" != 0 ]; then
        eval "[ \"\${$name_2746+x}\" = x ]"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_env_var_test117_v0=0
            return 0
        fi
    fi
    ret_env_var_test117_v0=1
    return 0
}

# env_var_set(name: Text, val: Text)
env_var_set__119_v0() {
    local name_287="${1}"
    local val_288="${2}"
    export $name_287="$val_288" 2> /dev/null
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_env_var_set119_v0=''
        return "${__status}"
    fi
}

# env_var_get(name: Text)
env_var_get__120_v0() {
    local name_9="${1}"
    if [ "$([ "_${EXEC_SHELL}" != "_bash" ]; echo $?)" != 0 ]; then
        local command_13
        command_13="$(printf "%s
" "${!name_9}")"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_env_var_get120_v0=''
            return "${__status}"
        fi
        ret_env_var_get120_v0="${command_13}"
        return 0
    elif [ "$([ "_${EXEC_SHELL}" != "_zsh" ]; echo $?)" != 0 ]; then
        local command_14
        command_14="$(printf "%s
" "${(P)name_9}")"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_env_var_get120_v0=''
            return "${__status}"
        fi
        ret_env_var_get120_v0="${command_14}"
        return 0
    elif [ "$([ "_${EXEC_SHELL}" != "_ksh" ]; echo $?)" != 0 ]; then
        local command_15
        command_15="$(eval "echo \${$name_9}")"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_env_var_get120_v0=''
            return "${__status}"
        fi
        ret_env_var_get120_v0="${command_15}"
        return 0
    fi
}

# is_command(command: Text)
is_command__122_v0() {
    local command_86="${1}"
    [ -x "$(command -v "${command_86}")" ]
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_is_command122_v0=0
        return 0
    fi
    ret_is_command122_v0=1
    return 0
}

# printf(format: Text, args: [Text])
printf__128_v0() {
    local format_31="${1}"
    local args_32=("${!2}")
    args_32=("${format_31}" "${args_32[@]}")
    __status=$?
    printf "${args_32[@]}"
    __status=$?
}

# echo_warning(message: Text)
echo_warning__137_v0() {
    local message_285="${1}"
    local array_16=("${message_285}")
    printf__128_v0 "\\x1b[1;3;97;43m%s\\x1b[0m
" array_16[@]
}

# echo_error(message: Text, exit_code: Int)
echo_error__138_v0() {
    local message_29="${1}"
    local exit_code_30="${2}"
    local array_17=("${message_29}")
    printf__128_v0 "\\x1b[1;3;97;41m%s\\x1b[0m
" array_17[@]
    if [ "$(( exit_code_30 > 0 ))" != 0 ]; then
        exit "${exit_code_30}"
    fi
}

command_18="$(tput tsl)"
__status=$?
tsl_4="${command_18}"
command_19="$(tput fsl)"
__status=$?
fsl_5="${command_19}"
command_20="$(tput smcup)"
__status=$?
smcup_6="${command_20}"
command_21="$(tput rmcup)"
__status=$?
rmcup_7="${command_21}"
env_var_get__120_v0 "TERM"
__status=$?
__TERM_10="${ret_env_var_get120_v0}"
# can_set_title()
can_set_title__169_v0() {
    local has_statusline_138=1
    tput hs
    __status=$?
    if [ "${__status}" != 0 ]; then
        starts_with__22_v0 "${__TERM_10}" "xterm"
        local ret_starts_with22_v0__22_12="${ret_starts_with22_v0}"
        if [ "${ret_starts_with22_v0__22_12}" != 0 ]; then
            TERM=xterm+sl tput hs
            __status=$?
            if [ "$(( __status == 0 ))" != 0 ]; then
                local command_22
                command_22="$(TERM=xterm+sl tput tsl)"
                __status=$?
                tsl_4="${command_22}"
                local command_23
                command_23="$(TERM=xterm+sl tput fsl)"
                __status=$?
                fsl_5="${command_23}"
            else
                has_statusline_138=0
            fi
        else
            has_statusline_138=0
        fi
    fi
    ret_can_set_title169_v0="${has_statusline_138}"
    return 0
}

# set_title(title: Text)
set_title__170_v0() {
    local title_137="${1}"
    can_set_title__169_v0 
    local ret_can_set_title169_v0__43_8="${ret_can_set_title169_v0}"
    if [ "${ret_can_set_title169_v0__43_8}" != 0 ]; then
        >&2 echo "${tsl_4}""${title_137}""${fsl_5}"
        __status=$?
    fi
}

# enter_alt_buffer()
enter_alt_buffer__171_v0() {
    >&2 echo ${smcup_6}
    __status=$?
}

# exit_alt_buffer()
exit_alt_buffer__172_v0() {
    >&2 echo ${rmcup_7}
    __status=$?
}

# teardown(failure: Bool)
teardown__173_v0() {
    local failure_2766="${1}"
    if [ "${failure_2766}" != 0 ]; then
        echo "Press any key to continue..."
        read -n 1
        __status=$?
    fi
    set_title__170_v0 ""
    exit_alt_buffer__172_v0 
}

__SELF_11=""
env_var_get__120_v0 "0"
__status=$?
me_12="${ret_env_var_get120_v0}"
text_contains__16_v0 "${me_12}" "/"
ret_text_contains16_v0__15_4="${ret_text_contains16_v0}"
if [ "${ret_text_contains16_v0__15_4}" != 0 ]; then
    starts_with__22_v0 "${me_12}" "/"
    ret_starts_with22_v0__16_12="${ret_starts_with22_v0}"
    if [ "$(( ! ret_starts_with22_v0__16_12 ))" != 0 ]; then
        env_var_get__120_v0 "PWD"
        __status=$?
        __PWD_21="${ret_env_var_get120_v0}"
        command_24="$(readlink ${me_12})"
        __status=$?
        if [ "${__status}" != 0 ]; then
            __SELF_11="${__PWD_21}/${me_12}"
        fi
        rl_22="${command_24}"
        starts_with__22_v0 "${rl_22}" "/"
        ret_starts_with22_v0__25_17="${ret_starts_with22_v0}"
        if [ "$([ "_${rl_22}" != "_" ]; echo $?)" != 0 ]; then
            __SELF_11="${__SELF_11}"
        elif [ "$(( ! ret_starts_with22_v0__25_17 ))" != 0 ]; then
            __SELF_11="${__PWD_21}/${rl_22}"
        else
            __SELF_11="${rl_22}"
        fi
    fi
else
    echo_error__138_v0 "This script must be run from an absolute or relative path." 1
fi
# exists_newer(left: Text, right: Text)
exists_newer__176_v0() {
    local left_2752="${1}"
    local right_2753="${2}"
    local command_25
    command_25="$(stat -c %W ${left_2752})"
    __status=$?
    parse_int__13_v0 "${command_25}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_exists_newer176_v0=0
        return 0
    fi
    local left_time_2755="${ret_parse_int13_v0}"
    local command_26
    command_26="$(stat -c %W ${right_2753})"
    __status=$?
    parse_int__13_v0 "${command_26}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_exists_newer176_v0=0
        return 0
    fi
    local right_time_2756="${ret_parse_int13_v0}"
    ret_exists_newer176_v0="$(( left_time_2755 >= right_time_2756 ))"
    return 0
}

# bail(message: Text, archive: Bool)
bail__177_v0() {
    local message_135="${1}"
    local archive_136="${2}"
    exit_alt_buffer__172_v0 
    set_title__170_v0 ""
    echo_error__138_v0 "${message_135}" 0
    if [ "${archive_136}" != 0 ]; then
        echo_error__138_v0 "This script can be rebuilt using the nixie tool." 0
    fi
    exit 1
    kill -ABRT $$
    __status=$?
}

# get_self()
get_self__178_v0() {
    ret_get_self178_v0="${__SELF_11}"
    return 0
}

# dump_archive()
dump_archive__179_v0() {
    local command_27
    command_27="$(mktemp -t nixie_XXXXXXXX.tar)"
    __status=$?
    local dest_134="${command_27}"
    cat ${__SELF_11} | (
        read -r M
        while ! [[ "$M" =~ ^-----BEGIN\ ARCHIVE\ SECTION----- ]]
        do read -r M || return 1
        done
        gzip -d -c 2>/dev/null > ${dest_134}
    )
    __status=$?
    if [ "${__status}" != 0 ]; then
        if [ "$(( __status != 2 ))" != 0 ]; then
            bail__177_v0 "Could not find the script's resource archive." 1
        fi
    fi
    ret_dump_archive179_v0="${dest_134}"
    return 0
}

# untar(member: Text, dump: Bool)
untar__180_v0() {
    local member_132="${1}"
    local dump_133="${2}"
    dump_archive__179_v0 
    local archive_139="${ret_dump_archive179_v0}"
    local tar_cmd_140="tar -x ${member_132} -f ${archive_139}"
    if [ "${dump_133}" != 0 ]; then
        tar_cmd_140="tar -x -O ${member_132} -f ${archive_139}"
    fi
    local command_28
    command_28="$(${tar_cmd_140})"
    __status=$?
    if [ "${__status}" != 0 ]; then
        local tar_status_141="${__status}"
        rm ${archive_139}
        __status=$?
        ret_untar180_v0=''
        return "${tar_status_141}"
    fi
    local tar_out_142="${command_28}"
    rm ${archive_139}
    __status=$?
    if [ "${dump_133}" != 0 ]; then
        ret_untar180_v0="${tar_out_142}"
        return 0
    else
        ret_untar180_v0="${member_132}"
        return 0
    fi
}

# check_deps(deps: [Text])
check_deps__181_v0() {
    local deps_83=("${!1}")
    local missing_84=()
    for dep_85 in "${deps_83[@]}"; do
        is_command__122_v0 "${dep_85}"
        local ret_is_command122_v0__139_16="${ret_is_command122_v0}"
        if [ "$(( ! ret_is_command122_v0__139_16 ))" != 0 ]; then
            missing_84+=("${dep_85}")
        fi
    done
    local __length_33=("${missing_84[@]}")
    if [ "$(( ${#__length_33[@]} > 0 ))" != 0 ]; then
        echo_error__138_v0 "The following commands are missing:" 0
        for cmd_87 in "${missing_84[@]}"; do
            echo_error__138_v0 "- ${cmd_87}" 0
        done
        echo_error__138_v0 "Use your distribution's package manager to install them, then try again." 0
        ret_check_deps181_v0=''
        return 1
    fi
}

# get_osname()
get_osname__190_v0() {
    local command_36
    command_36="$(uname -s)"
    __status=$?
    ret_get_osname190_v0="${command_36}"
    return 0
}

# get_machine()
get_machine__191_v0() {
    local command_37
    command_37="$(uname -m)"
    __status=$?
    ret_get_machine191_v0="${command_37}"
    return 0
}

# get_system()
get_system__192_v0() {
    get_osname__190_v0 
    local osname_2761="${ret_get_osname190_v0}"
    get_machine__191_v0 
    local machine_2762="${ret_get_machine191_v0}"
    ret_get_system192_v0="${osname_2761}.${machine_2762}"
    return 0
}

# get_nix_root()
get_nix_root__194_v0() {
    env_var_get__120_v0 "HOME"
    __status=$?
    local userhome_266="${ret_env_var_get120_v0}"
    get_osname__190_v0 
    local osname_267="${ret_get_osname190_v0}"
    local result_268=""
    if [ "$([ "_${osname_267}" != "_Darwin" ]; echo $?)" != 0 ]; then
        result_268="${userhome_266}/Library/Nix"
    else
        result_268="${userhome_266}/.local/share/nix/root"
    fi
    mkdir -p ${result_268}
    __status=$?
    ret_get_nix_root194_v0="${result_268}"
    return 0
}

# get_cache_root()
get_cache_root__195_v0() {
    env_var_get__120_v0 "HOME"
    __status=$?
    local userhome_270="${ret_env_var_get120_v0}"
    get_osname__190_v0 
    local osname_271="${ret_get_osname190_v0}"
    local result_272=""
    if [ "$([ "_${osname_271}" != "_Darwin" ]; echo $?)" != 0 ]; then
        result_272="${userhome_270}/Library/Caches"
    else
        result_272="${userhome_270}/.cache"
    fi
    mkdir -p ${result_272}
    __status=$?
    ret_get_cache_root195_v0="${result_272}"
    return 0
}

# get_repo_root()
get_repo_root__196_v0() {
    get_self__178_v0 
    local ret_get_self178_v0__80_24="${ret_get_self178_v0}"
    split__4_v0 "${ret_get_self178_v0__80_24}" "/"
    local self_a_277=("${ret_split4_v0[@]}")
    array_pop__74_v0 "self_a_277"
    __status=$?
    join__7_v0 self_a_277[@] "/"
    local ret_join7_v0__83_26="${ret_join7_v0}"
    local self_dir_284="/""${ret_join7_v0__83_26}"
    local command_38
    command_38="$(git -C ${self_dir_284} rev-parse --show-toplevel)"
    __status=$?
    if [ "${__status}" != 0 ]; then
        echo_warning__137_v0 "Failed to find current Git repository, using script parent directory."
        ret_get_repo_root196_v0="${self_dir_284}"
        return 0
    fi
    ret_get_repo_root196_v0="${command_38}"
    return 0
}

__SOURCE_CACHE_33=""
__NIX_BINS_DERIVATION_35=""
__EXTRA_FEATURES_36=""
__EXTRA_SUBSTITUTERS_37=""
__EXTRA_TRUSTED_PUBLIC_KEYS_38=""
__NIXIE_VERSION_39=""
# load_features()
load_features__212_v0() {
    untar__180_v0 "features" 1
    __status=$?
    if [ "${__status}" != 0 ]; then
        bail__177_v0 "The resource archive is missing or malformed." 1
    fi
    local envfile_143="${ret_untar180_v0}"
    eval ${envfile_143}
    __status=$?
    if [ "${__status}" != 0 ]; then
        bail__177_v0 "The environment file in the resource archive is malformed." 1
    fi
    env_var_get__120_v0 "SOURCE_CACHE"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_load_features212_v0=''
        return "${__status}"
    fi
    __SOURCE_CACHE_33="${ret_env_var_get120_v0}"
    env_var_get__120_v0 "SOURCE_DERIVATION"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_load_features212_v0=''
        return "${__status}"
    fi
    env_var_get__120_v0 "NIX_BINS_DERIVATION"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_load_features212_v0=''
        return "${__status}"
    fi
    __NIX_BINS_DERIVATION_35="${ret_env_var_get120_v0}"
    env_var_get__120_v0 "EXTRA_FEATURES"
    __status=$?
    __EXTRA_FEATURES_36="${ret_env_var_get120_v0}"
    env_var_get__120_v0 "EXTRA_SUBSTITUTERS"
    __status=$?
    __EXTRA_SUBSTITUTERS_37="${ret_env_var_get120_v0}"
    env_var_get__120_v0 "EXTRA_TRUSTED_PUBLIC_KEYS"
    __status=$?
    __EXTRA_TRUSTED_PUBLIC_KEYS_38="${ret_env_var_get120_v0}"
    env_var_get__120_v0 "NIXIE_VERSION"
    __status=$?
    __NIXIE_VERSION_39="${ret_env_var_get120_v0}"
}

# cmd_help()
cmd_help__213_v0() {
    echo "Nix wrapper script, generated by Nixie ${__NIXIE_VERSION_39}"
    printf '%s\n' ""
    echo "Available --nixie- options:"
    echo "  --nixie-help            Show this help message and exit."
    echo "  --nixie-print-config    Print this script's configuration."
    echo "  --nixie-extract         Unpack the resources archive into nixie/"
    echo "  --nixie-cleanup         Delete local Nix build files"
    echo "  --nixie-ignore-system   Behave as if Nix was not installed."
    exit 0
}

# cmd_print_config()
cmd_print_config__214_v0() {
    untar__180_v0 "features" 1
    __status=$?
    local ret_untar180_v0__31_16="${ret_untar180_v0}"
    printf '%s\n' "${ret_untar180_v0__31_16}"
    exit 0
}

# cmd_extract()
cmd_extract__215_v0() {
    dir_create__44_v0 "nixie"
    __status=$?
    cd "nixie"
    __status=$?
    untar__180_v0 "" 0
    __status=$?
    exit 0
}

# cmd_cleanup()
cmd_cleanup__216_v0() {
    get_nix_root__194_v0 
    local nix_root_269="${ret_get_nix_root194_v0}"
    get_cache_root__195_v0 
    local cache_root_273="${ret_get_cache_root195_v0}"
    get_repo_root__196_v0 
    local repo_root_286="${ret_get_repo_root196_v0}"
    echo "Removing local Nix channels and build files..."
    chmod -R +wx ${repo_root_286}/.nixie 2>/dev/null
    __status=$?
    rm -rf ${repo_root_286}/.nixie
    __status=$?
    echo "Removing user Nix store..."
    chmod -R +wx ${nix_root_269} 2>/dev/null
    __status=$?
    rm -rf ${nix_root_269}
    __status=$?
    echo "Removing retrieved Nix binaries..."
    rm -rf ${cache_root_273}/nix-static ${cache_root_273}/nix-lib ${cache_root_273}/nix-deps
    __status=$?
    exit 0
}

# opt_ignore_system()
opt_ignore_system__217_v0() {
    >&2 echo "Ignoring system-wide Nix for testing purposes."
    __status=$?
    >&2 echo "Re-run without the --nixie-ignore-system flag to import the single-user"
    __status=$?
    >&2 echo "Nix store into the system store."
    __status=$?
    env_var_set__119_v0 "nosystem" "1"
    __status=$?
}

# opt_no_precompiled()
opt_no_precompiled__218_v0() {
    >&2 echo "Ignoring precompiled binaries for testing purposes."
    __status=$?
    >&2 echo "This implies --nixie-ignore-system."
    __status=$?
    env_var_set__119_v0 "nobins" "1"
    __status=$?
    env_var_set__119_v0 "nosystem" "1"
    __status=$?
}

# notfound(cmd: Text)
notfound__219_v0() {
    local cmd_289="${1}"
    env_var_get__120_v0 "0"
    __status=$?
    local self_290="${ret_env_var_get120_v0}"
    echo_error__138_v0 "No such option: --nixie-${cmd_289}. Run '${self_290} --nixie-help' for available options." 1
}

# eval_cmd(cmd: Text)
eval_cmd__220_v0() {
    local cmd_263="${1}"
    if [ "$([ "_${cmd_263}" != "_help" ]; echo $?)" != 0 ]; then
        cmd_help__213_v0 
    elif [ "$([ "_${cmd_263}" != "_print-config" ]; echo $?)" != 0 ]; then
        cmd_print_config__214_v0 
    elif [ "$([ "_${cmd_263}" != "_extract" ]; echo $?)" != 0 ]; then
        cmd_extract__215_v0 
    elif [ "$([ "_${cmd_263}" != "_cleanup" ]; echo $?)" != 0 ]; then
        cmd_cleanup__216_v0 
    elif [ "$([ "_${cmd_263}" != "_ignore-system" ]; echo $?)" != 0 ]; then
        opt_ignore_system__217_v0 
    elif [ "$([ "_${cmd_263}" != "_no-precompiled" ]; echo $?)" != 0 ]; then
        opt_no_precompiled__218_v0 
    else
        notfound__219_v0 "${cmd_263}"
    fi
}

# catch_args(args: [Text])
catch_args__221_v0() {
    local -n args_255="${1}"
    local local_args_256=("${args_255[@]}")
    args_255=()
    for arg_257 in "${local_args_256[@]}"; do
        local cmd_258=""
        starts_with__22_v0 "${arg_257}" "--nixie-"
        local ret_starts_with22_v0__109_12="${ret_starts_with22_v0}"
        if [ "${ret_starts_with22_v0__109_12}" != 0 ]; then
            local __length_42="--nixie-"
            slice__24_v0 "${arg_257}" "${#__length_42}" 0
            cmd_258="${ret_slice24_v0}"
            eval_cmd__220_v0 "${cmd_258}"
        else
            args_255+=("${arg_257}")
        fi
    done
}

# file_download(url: Text, path: Text)
file_download__324_v0() {
    local url_2773="${1}"
    local path_2774="${2}"
    is_command__122_v0 "curl"
    local ret_is_command122_v0__15_9="${ret_is_command122_v0}"
    is_command__122_v0 "wget"
    local ret_is_command122_v0__18_9="${ret_is_command122_v0}"
    is_command__122_v0 "aria2c"
    local ret_is_command122_v0__21_9="${ret_is_command122_v0}"
    if [ "${ret_is_command122_v0__15_9}" != 0 ]; then
        curl -L -o "${path_2774}" "${url_2773}" >/dev/null 2>&1
        __status=$?
    elif [ "${ret_is_command122_v0__18_9}" != 0 ]; then
        wget "${url_2773}" -P "${path_2774}" >/dev/null 2>&1
        __status=$?
    elif [ "${ret_is_command122_v0__21_9}" != 0 ]; then
        aria2c "${url_2773}" -d "${path_2774}" >/dev/null 2>&1
        __status=$?
    else
        ret_file_download324_v0=''
        return 1
    fi
}

# cachix_url(derivation: Text, member: Text)
cachix_url__331_v0() {
    local derivation_2771="${1}"
    local member_2772="${2}"
    ret_cachix_url331_v0="https://${__SOURCE_CACHE_33}/serve/${derivation_2771}/${member_2772}"
    return 0
}

# pull_binary(member: Text, dest: Text)
pull_binary__333_v0() {
    local member_2767="${1}"
    local dest_2768="${2}"
    untar__180_v0 "${member_2767}" 0
    __status=$?
    local where_2769="${ret_untar180_v0}"
    if [ "$(( __status != 0 ))" != 0 ]; then
        local command_44
        command_44="$(mktemp -t nixie_${member_2767}_XXXXXXXX)"
        __status=$?
        local tmpf_2770="${command_44}"
        cachix_url__331_v0 "${__NIX_BINS_DERIVATION_35}" "${member_2767}"
        local ret_cachix_url331_v0__84_23="${ret_cachix_url331_v0}"
        file_download__324_v0 "${ret_cachix_url331_v0__84_23}" "${tmpf_2770}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_pull_binary333_v0=''
            return "${__status}"
        fi
        where_2769="${tmpf_2770}"
    fi
    mv "${where_2769}" "${dest_2768}"
    __status=$?
}

command_45="$(tput tsl)"
__status=$?
tsl_44="${command_45}"
command_46="$(tput fsl)"
__status=$?
fsl_45="${command_46}"
command_47="$(tput smcup)"
__status=$?
command_48="$(tput rmcup)"
__status=$?
env_var_get__120_v0 "TERM"
__status=$?
__TERM_48="${ret_env_var_get120_v0}"
# can_set_title()
can_set_title__348_v0() {
    local has_statusline_2790=1
    tput hs
    __status=$?
    if [ "${__status}" != 0 ]; then
        starts_with__22_v0 "${__TERM_48}" "xterm"
        local ret_starts_with22_v0__22_12="${ret_starts_with22_v0}"
        if [ "${ret_starts_with22_v0__22_12}" != 0 ]; then
            TERM=xterm+sl tput hs
            __status=$?
            if [ "$(( __status == 0 ))" != 0 ]; then
                local command_49
                command_49="$(TERM=xterm+sl tput tsl)"
                __status=$?
                tsl_44="${command_49}"
                local command_50
                command_50="$(TERM=xterm+sl tput fsl)"
                __status=$?
                fsl_45="${command_50}"
            else
                has_statusline_2790=0
            fi
        else
            has_statusline_2790=0
        fi
    fi
    ret_can_set_title348_v0="${has_statusline_2790}"
    return 0
}

# set_title(title: Text)
set_title__349_v0() {
    local title_2789="${1}"
    can_set_title__348_v0 
    local ret_can_set_title348_v0__43_8="${ret_can_set_title348_v0}"
    if [ "${ret_can_set_title348_v0__43_8}" != 0 ]; then
        >&2 echo "${tsl_44}""${title_2789}""${fsl_45}"
        __status=$?
    fi
}

command_51="$(tput tsl)"
__status=$?
tsl_49="${command_51}"
command_52="$(tput fsl)"
__status=$?
fsl_50="${command_52}"
command_53="$(tput smcup)"
__status=$?
command_54="$(tput rmcup)"
__status=$?
rmcup_52="${command_54}"
env_var_get__120_v0 "TERM"
__status=$?
__TERM_53="${ret_env_var_get120_v0}"
# can_set_title()
can_set_title__368_v0() {
    local has_statusline_2802=1
    tput hs
    __status=$?
    if [ "${__status}" != 0 ]; then
        starts_with__22_v0 "${__TERM_53}" "xterm"
        local ret_starts_with22_v0__22_12="${ret_starts_with22_v0}"
        if [ "${ret_starts_with22_v0__22_12}" != 0 ]; then
            TERM=xterm+sl tput hs
            __status=$?
            if [ "$(( __status == 0 ))" != 0 ]; then
                local command_55
                command_55="$(TERM=xterm+sl tput tsl)"
                __status=$?
                tsl_49="${command_55}"
                local command_56
                command_56="$(TERM=xterm+sl tput fsl)"
                __status=$?
                fsl_50="${command_56}"
            else
                has_statusline_2802=0
            fi
        else
            has_statusline_2802=0
        fi
    fi
    ret_can_set_title368_v0="${has_statusline_2802}"
    return 0
}

# set_title(title: Text)
set_title__369_v0() {
    local title_2801="${1}"
    can_set_title__368_v0 
    local ret_can_set_title368_v0__43_8="${ret_can_set_title368_v0}"
    if [ "${ret_can_set_title368_v0__43_8}" != 0 ]; then
        >&2 echo "${tsl_49}""${title_2801}""${fsl_50}"
        __status=$?
    fi
}

# exit_alt_buffer()
exit_alt_buffer__371_v0() {
    >&2 echo ${rmcup_52}
    __status=$?
}

__SELF_54=""
env_var_get__120_v0 "0"
__status=$?
me_55="${ret_env_var_get120_v0}"
text_contains__16_v0 "${me_55}" "/"
ret_text_contains16_v0__15_4="${ret_text_contains16_v0}"
if [ "${ret_text_contains16_v0__15_4}" != 0 ]; then
    starts_with__22_v0 "${me_55}" "/"
    ret_starts_with22_v0__16_12="${ret_starts_with22_v0}"
    if [ "$(( ! ret_starts_with22_v0__16_12 ))" != 0 ]; then
        env_var_get__120_v0 "PWD"
        __status=$?
        __PWD_56="${ret_env_var_get120_v0}"
        command_57="$(readlink ${me_55})"
        __status=$?
        if [ "${__status}" != 0 ]; then
            __SELF_54="${__PWD_56}/${me_55}"
        fi
        rl_57="${command_57}"
        starts_with__22_v0 "${rl_57}" "/"
        ret_starts_with22_v0__25_17="${ret_starts_with22_v0}"
        if [ "$([ "_${rl_57}" != "_" ]; echo $?)" != 0 ]; then
            __SELF_54="${__SELF_54}"
        elif [ "$(( ! ret_starts_with22_v0__25_17 ))" != 0 ]; then
            __SELF_54="${__PWD_56}/${rl_57}"
        else
            __SELF_54="${rl_57}"
        fi
    fi
else
    echo_error__138_v0 "This script must be run from an absolute or relative path." 1
fi
# bail(message: Text, archive: Bool)
bail__376_v0() {
    local message_2799="${1}"
    local archive_2800="${2}"
    exit_alt_buffer__371_v0 
    set_title__369_v0 ""
    echo_error__138_v0 "${message_2799}" 0
    if [ "${archive_2800}" != 0 ]; then
        echo_error__138_v0 "This script can be rebuilt using the nixie tool." 0
    fi
    exit 1
    kill -ABRT $$
    __status=$?
}

# get_self()
get_self__377_v0() {
    ret_get_self377_v0="${__SELF_54}"
    return 0
}

# dump_archive()
dump_archive__378_v0() {
    local command_58
    command_58="$(mktemp -t nixie_XXXXXXXX.tar)"
    __status=$?
    local dest_2798="${command_58}"
    cat ${__SELF_54} | (
        read -r M
        while ! [[ "$M" =~ ^-----BEGIN\ ARCHIVE\ SECTION----- ]]
        do read -r M || return 1
        done
        gzip -d -c 2>/dev/null > ${dest_2798}
    )
    __status=$?
    if [ "${__status}" != 0 ]; then
        if [ "$(( __status != 2 ))" != 0 ]; then
            bail__376_v0 "Could not find the script's resource archive." 1
        fi
    fi
    ret_dump_archive378_v0="${dest_2798}"
    return 0
}

# untar(member: Text, dump: Bool)
untar__379_v0() {
    local member_2796="${1}"
    local dump_2797="${2}"
    dump_archive__378_v0 
    local archive_2803="${ret_dump_archive378_v0}"
    local tar_cmd_2804="tar -x ${member_2796} -f ${archive_2803}"
    if [ "${dump_2797}" != 0 ]; then
        tar_cmd_2804="tar -x -O ${member_2796} -f ${archive_2803}"
    fi
    local command_59
    command_59="$(${tar_cmd_2804})"
    __status=$?
    if [ "${__status}" != 0 ]; then
        local tar_status_2805="${__status}"
        rm ${archive_2803}
        __status=$?
        ret_untar379_v0=''
        return "${tar_status_2805}"
    fi
    local tar_out_2806="${command_59}"
    rm ${archive_2803}
    __status=$?
    if [ "${dump_2797}" != 0 ]; then
        ret_untar379_v0="${tar_out_2806}"
        return 0
    else
        ret_untar379_v0="${member_2796}"
        return 0
    fi
}

# get_osname()
get_osname__382_v0() {
    local command_60
    command_60="$(uname -s)"
    __status=$?
    ret_get_osname382_v0="${command_60}"
    return 0
}

# get_dll_ext()
get_dll_ext__385_v0() {
    get_osname__382_v0 
    local osname_2813="${ret_get_osname382_v0}"
    if [ "$([ "_${osname_2813}" != "_Darwin" ]; echo $?)" != 0 ]; then
        ret_get_dll_ext385_v0="dylib"
        return 0
    else
        ret_get_dll_ext385_v0="so"
        return 0
    fi
}

# get_cache_root()
get_cache_root__387_v0() {
    env_var_get__120_v0 "HOME"
    __status=$?
    local userhome_2784="${ret_env_var_get120_v0}"
    get_osname__382_v0 
    local osname_2785="${ret_get_osname382_v0}"
    local result_2786=""
    if [ "$([ "_${osname_2785}" != "_Darwin" ]; echo $?)" != 0 ]; then
        result_2786="${userhome_2784}/Library/Caches"
    else
        result_2786="${userhome_2784}/.cache"
    fi
    mkdir -p ${result_2786}
    __status=$?
    ret_get_cache_root387_v0="${result_2786}"
    return 0
}

# get_repo_root()
get_repo_root__388_v0() {
    get_self__377_v0 
    local ret_get_self377_v0__80_24="${ret_get_self377_v0}"
    split__4_v0 "${ret_get_self377_v0__80_24}" "/"
    local self_a_2779=("${ret_split4_v0[@]}")
    array_pop__74_v0 "self_a_2779"
    __status=$?
    join__7_v0 self_a_2779[@] "/"
    local ret_join7_v0__83_26="${ret_join7_v0}"
    local self_dir_2780="/""${ret_join7_v0__83_26}"
    local command_61
    command_61="$(git -C ${self_dir_2780} rev-parse --show-toplevel)"
    __status=$?
    if [ "${__status}" != 0 ]; then
        echo_warning__137_v0 "Failed to find current Git repository, using script parent directory."
        ret_get_repo_root388_v0="${self_dir_2780}"
        return 0
    fi
    ret_get_repo_root388_v0="${command_61}"
    return 0
}

# get_source_root()
get_source_root__392_v0() {
    get_repo_root__388_v0 
    local repo_root_2781="${ret_get_repo_root388_v0}"
    ret_get_source_root392_v0="${repo_root_2781}/.nixie/sources"
    return 0
}

__SOURCE_CACHE_61=""
__SOURCE_DERIVATION_62=""
# cachix_url(derivation: Text, member: Text)
cachix_url__408_v0() {
    local derivation_2811="${1}"
    local member_2812="${2}"
    ret_cachix_url408_v0="https://${__SOURCE_CACHE_61}/serve/${derivation_2811}/${member_2812}"
    return 0
}

# pull_source_file(member: Text, dest: Text)
pull_source_file__409_v0() {
    local member_2792="${1}"
    local dest_2793="${2}"
    local where_2794=""
    local my_status_2795=1
    env_var_test__117_v0 "_NIXIE_TESTING_SKIP_TARBALL"
    local ret_env_var_test117_v0__33_12="${ret_env_var_test117_v0}"
    if [ "$(( ! ret_env_var_test117_v0__33_12 ))" != 0 ]; then
        untar__379_v0 "sources/${member_2792}" 0
        __status=$?
        where_2794="${ret_untar379_v0}"
        my_status_2795="${__status}"
    fi
    env_var_test__117_v0 "_NIXIE_TESTING_SOURCES_DIR"
    local ret_env_var_test117_v0__38_8="${ret_env_var_test117_v0}"
    if [ "$(( ret_env_var_test117_v0__38_8 && $(( my_status_2795 != 0 )) ))" != 0 ]; then
        env_var_get__120_v0 "_NIXIE_TESTING_SOURCES_DIR"
        __status=$?
        local srcdir_2807="${ret_env_var_get120_v0}"
        local command_62
        command_62="$(mktemp -t -d nixie_${member_2792}_XXXXXXXX)"
        __status=$?
        local tmpd_2808="${command_62}"
        file_exists__39_v0 "${srcdir_2807}/${member_2792}.tar.gz"
        local ret_file_exists39_v0__42_12="${ret_file_exists39_v0}"
        if [ "${ret_file_exists39_v0__42_12}" != 0 ]; then
            gzip -d -c ${srcdir_2807}/${member_2792}.tar.gz | tar -x -C ${tmpd_2808}
            __status=$?
            my_status_2795="${__status}"
            where_2794="${tmpd_2808}/${member_2792}"
        else
            my_status_2795=1
        fi
    fi
    if [ "$(( my_status_2795 != 0 ))" != 0 ]; then
        local command_63
        command_63="$(mktemp -t nixie_src_XXXXXXXX.tgz)"
        __status=$?
        local tmpf_2809="${command_63}"
        local command_64
        command_64="$(mktemp -t -d nixie_${member_2792}_XXXXXXXX)"
        __status=$?
        local tmpd_2810="${command_64}"
        cachix_url__408_v0 "${__SOURCE_DERIVATION_62}" "${member_2792}.tar.gz"
        local ret_cachix_url408_v0__55_23="${ret_cachix_url408_v0}"
        file_download__324_v0 "${ret_cachix_url408_v0__55_23}" "${tmpf_2809}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_pull_source_file409_v0=''
            return "${__status}"
        fi
        gzip -d -c ${tmpf_2809} | tar -x -C ${tmpd_2810}
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_pull_source_file409_v0=''
            return "${__status}"
        fi
        rm -f ${tmpf_2809}
        __status=$?
        where_2794="${tmpd_2810}/${member_2792}"
    fi
    rm -rf ${dest_2793}
    __status=$?
    mv "${where_2794}" "${dest_2793}"
    __status=$?
}

step_total_71=1
step_current_72=1
# pkg_exists(package: Text)
pkg_exists__414_v0() {
    local package_2791="${1}"
    pkg-config ${package_2791}
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_pkg_exists414_v0=0
        return 0
    fi
    ret_pkg_exists414_v0=1
    return 0
}

# step_title(name: Text)
step_title__415_v0() {
    local name_2788="${1}"
    clear
    __status=$?
    set_title__349_v0 "Building Nix: ${name_2788} (${step_current_72}/${step_total_71})"
    step_current_72="$(( step_current_72 + 1 ))"
}

# get_source_root()
get_source_root__416_v0() {
    get_repo_root__388_v0 
    local repo_root_2782="${ret_get_repo_root388_v0}"
    ret_get_source_root416_v0="${repo_root_2782}/.nixie/sources"
    return 0
}

# build_openssl_inner()
build_openssl_inner__420_v0() {
    get_dll_ext__385_v0 
    local dll_ext_2814="${ret_get_dll_ext385_v0}"
    get_cache_root__387_v0 
    local cache_root_2815="${ret_get_cache_root387_v0}"
    chmod +x ./config
    __status=$?
    ./config
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl_inner420_v0=''
        return "${__status}"
    fi
    local command_67
    command_67="$(grep ".*\.h:" ./Makefile | cut -f 1 -d :)"
    __status=$?
    split_lines__5_v0 "${command_67}"
    local ret_split_lines5_v0__25_19=("${ret_split_lines5_v0[@]}")
    for header_2817 in "${ret_split_lines5_v0__25_19[@]}"; do
        make ${header_2817}
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_build_openssl_inner420_v0=''
            return "${__status}"
        fi
    done
    local command_70
    command_70="$(grep ".*\.inc:" ./Makefile | cut -f 1 -d :)"
    __status=$?
    split_lines__5_v0 "${command_70}"
    local ret_split_lines5_v0__28_17=("${ret_split_lines5_v0[@]}")
    for hinc_2818 in "${ret_split_lines5_v0__28_17[@]}"; do
        make ${hinc_2818}
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_build_openssl_inner420_v0=''
            return "${__status}"
        fi
    done
    make libcrypto.${dll_ext_2814} libcrypto.pc
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl_inner420_v0=''
        return "${__status}"
    fi
    cp ./libcrypto.* ${cache_root_2815}/nix-deps/lib/
    __status=$?
    cp ./libcrypto.pc ${cache_root_2815}/nix-deps/lib/pkgconfig
    __status=$?
    cp -r ./include ${cache_root_2815}/nix-deps/
    __status=$?
}

# build_openssl()
build_openssl__421_v0() {
    get_source_root__416_v0 
    local source_root_2783="${ret_get_source_root416_v0}"
    get_cache_root__387_v0 
    step_title__415_v0 "libcrypto"
    pkg_exists__414_v0 "libcrypto"
    local ret_pkg_exists414_v0__53_8="${ret_pkg_exists414_v0}"
    if [ "${ret_pkg_exists414_v0__53_8}" != 0 ]; then
        ret_build_openssl421_v0=0
        return 0
    fi
    env_var_test__117_v0 "OPENSSL_LIBS"
    local ret_env_var_test117_v0__55_8="${ret_env_var_test117_v0}"
    env_var_test__117_v0 "OPENSSL_CFLAGS"
    local ret_env_var_test117_v0__55_41="${ret_env_var_test117_v0}"
    if [ "$(( ret_env_var_test117_v0__55_8 && ret_env_var_test117_v0__55_41 ))" != 0 ]; then
        ret_build_openssl421_v0=0
        return 0
    fi
    pull_source_file__409_v0 "openssl" "${source_root_2783}/openssl"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl421_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2783}/openssl && build_openssl_inner__420_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl421_v0=''
        return "${__status}"
    fi
}

# macos_build_post()
macos_build_post__430_v0() {
    cc -shared -o liblowdown.1.dylib *.o
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_macos_build_post430_v0=''
        return "${__status}"
    fi
}

# build_lowdown_inner()
build_lowdown_inner__431_v0() {
    get_cache_root__387_v0 
    local cache_root_2832="${ret_get_cache_root387_v0}"
    ./configure PREFIX=${cache_root_2832}/nix-deps
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown_inner431_v0=''
        return "${__status}"
    fi
    make
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown_inner431_v0=''
        return "${__status}"
    fi
    get_osname__382_v0 
    local ret_get_osname382_v0__26_8="${ret_get_osname382_v0}"
    if [ "$([ "_${ret_get_osname382_v0__26_8}" != "_Darwin" ]; echo $?)" != 0 ]; then
        macos_build_post__430_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_build_lowdown_inner431_v0=''
            return "${__status}"
        fi
    fi
    make install_shared
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown_inner431_v0=''
        return "${__status}"
    fi
}

# build_lowdown()
build_lowdown__432_v0() {
    get_source_root__416_v0 
    local source_root_2830="${ret_get_source_root416_v0}"
    get_cache_root__387_v0 
    step_title__415_v0 "lowdown"
    pkg_exists__414_v0 "lowdown"
    local ret_pkg_exists414_v0__41_8="${ret_pkg_exists414_v0}"
    if [ "${ret_pkg_exists414_v0__41_8}" != 0 ]; then
        ret_build_lowdown432_v0=0
        return 0
    fi
    pull_source_file__409_v0 "lowdown" "${source_root_2830}/lowdown"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown432_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2830}/lowdown && build_lowdown_inner__431_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown432_v0=''
        return "${__status}"
    fi
}

# build_nlohmann_json()
build_nlohmann_json__441_v0() {
    get_source_root__416_v0 
    local source_root_2825="${ret_get_source_root416_v0}"
    get_cache_root__387_v0 
    local cache_root_2826="${ret_get_cache_root387_v0}"
    step_title__415_v0 "nlohmann_json"
    pkg_exists__414_v0 "nlohmann_json"
    local ret_pkg_exists414_v0__21_8="${ret_pkg_exists414_v0}"
    if [ "${ret_pkg_exists414_v0__21_8}" != 0 ]; then
        ret_build_nlohmann_json441_v0=0
        return 0
    fi
    pull_source_file__409_v0 "nlohmann_json" "${source_root_2825}/nlohmann_json"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nlohmann_json441_v0=''
        return "${__status}"
    fi
    local command_71
    command_71="$(grep "^version:" ${source_root_2825}/nlohmann_json/wsjcpp.yml | cut -d '"' -f 2 | cut -d 'v' -f 2)"
    __status=$?
    local version_2827="${command_71}"
    file_write__41_v0 "${cache_root_2826}/nix-deps/lib/pkgconfig/nlohmann_json.pc" "Name: nlohmann_json
Version: ${version_2827}
Description: JSON for Modern C++
Cflags: -I${source_root_2825}/nlohmann_json/include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nlohmann_json441_v0=''
        return "${__status}"
    fi
}

modules_73=("predef" "chrono" "container" "context" "coroutine" "system" "thread")
# find_boost_libs(libs: [Text])
find_boost_libs__450_v0() {
    local libs_2820=("${!1}")
    for lib_2821 in "${libs_2820[@]}"; do
        local libname_2822="libboost_${lib_2821}*"
        file_exists__39_v0 "/usr/lib/${libname_2822}"
        local ret_file_exists39_v0__23_20="${ret_file_exists39_v0}"
        file_exists__39_v0 "/usr/local/lib/${libname_2822}"
        local ret_file_exists39_v0__24_20="${ret_file_exists39_v0}"
        if [ "$(( ! $(( ret_file_exists39_v0__23_20 || ret_file_exists39_v0__24_20 )) ))" != 0 ]; then
            ret_find_boost_libs450_v0=0
            return 0
        fi
        dir_exists__38_v0 "/usr/include/boost/${lib_2821}"
        local ret_dir_exists38_v0__26_20="${ret_dir_exists38_v0}"
        dir_exists__38_v0 "/usr/local/include/boost/${lib_2821}"
        local ret_dir_exists38_v0__27_20="${ret_dir_exists38_v0}"
        if [ "$(( ! $(( ret_dir_exists38_v0__26_20 || ret_dir_exists38_v0__27_20 )) ))" != 0 ]; then
            ret_find_boost_libs450_v0=0
            return 0
        fi
    done
    ret_find_boost_libs450_v0=1
    return 0
}

# build_boost_inner()
build_boost_inner__451_v0() {
    local args_2823=("variant=release" "link=static" "--stagedir=.")
    for mod_2824 in "${modules_73[@]}"; do
        args_2823+=("--with-${mod_2824}")
    done
    ./bootstrap.sh
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost_inner451_v0=''
        return "${__status}"
    fi
    ./b2 "${args_2823[@]}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost_inner451_v0=''
        return "${__status}"
    fi
}

# build_boost()
build_boost__452_v0() {
    get_source_root__416_v0 
    local source_root_2819="${ret_get_source_root416_v0}"
    step_title__415_v0 "boost"
    local array_79=("atomic")
    local array_add_80=("${array_79[@]}" "${modules_73[@]}")
    find_boost_libs__450_v0 array_add_80[@]
    local ret_find_boost_libs450_v0__56_8="${ret_find_boost_libs450_v0}"
    if [ "${ret_find_boost_libs450_v0__56_8}" != 0 ]; then
        ret_build_boost452_v0=0
        return 0
    fi
    pull_source_file__409_v0 "boost" "${source_root_2819}/boost"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost452_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2819}/boost && build_boost_inner__451_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost452_v0=''
        return "${__status}"
    fi
    env_var_set__119_v0 "BOOST_ROOT" "${source_root_2819}/boost"
    __status=$?
    export BOOST_ROOT
    __status=$?
}

# build_autoconf_dep(lib_name: Text, inc_prefix: Text)
build_autoconf_dep__460_v0() {
    local lib_name_2833="${1}"
    local inc_prefix_2834="${2}"
    get_source_root__416_v0 
    local source_root_2835="${ret_get_source_root416_v0}"
    get_cache_root__387_v0 
    local cache_root_2836="${ret_get_cache_root387_v0}"
    local my_source_2837="${source_root_2835}/${lib_name_2833}"
    step_title__415_v0 "${lib_name_2833}"
    pkg_exists__414_v0 "${lib_name_2833}"
    local ret_pkg_exists414_v0__26_8="${ret_pkg_exists414_v0}"
    if [ "${ret_pkg_exists414_v0__26_8}" != 0 ]; then
        ret_build_autoconf_dep460_v0=''
        return 0
    fi
    pull_source_file__409_v0 "${lib_name_2833}" "${my_source_2837}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_autoconf_dep460_v0=''
        return "${__status}"
    fi
    ( unset C_INCLUDE_PATH CPLUS_INCLUDE_PATH     && cd ${my_source_2837}     && ./configure --prefix=${cache_root_2836}/nix-deps     && make && make install )
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_autoconf_dep460_v0=''
        return "${__status}"
    fi
}

# build_nix_inner()
build_nix_inner__470_v0() {
    get_source_root__416_v0 
    local source_root_2841="${ret_get_source_root416_v0}"
    local venv_2842="${source_root_2841}/nix/venv"
    mkdir build && cd build
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix_inner470_v0=''
        return "${__status}"
    fi
    ${venv_2842}/bin/meson setup -Dlibstore:seccomp-sandboxing=disabled                             -Dlibcmd:readline-flavor=editline                             -Dlibexpr:gc=disabled                             -Dlibutil:cpuid=disabled                             -Ddoc-gen=false                             -Dunit-tests=false                             -Dbindings=false                             ..
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix_inner470_v0=''
        return "${__status}"
    fi
    ${venv_2842}/bin/ninja
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix_inner470_v0=''
        return "${__status}"
    fi
}

# build_nix()
build_nix__471_v0() {
    get_source_root__416_v0 
    local source_root_2838="${ret_get_source_root416_v0}"
    get_cache_root__387_v0 
    local cache_root_2839="${ret_get_cache_root387_v0}"
    local venv_2840="${source_root_2838}/nix/venv"
    step_title__415_v0 "nix"
    pull_source_file__409_v0 "nix" "${source_root_2838}/nix"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix471_v0=''
        return "${__status}"
    fi
    python3 -m venv --system-site-packages "${venv_2840}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix471_v0=''
        return "${__status}"
    fi
    export LIBRARY_PATH=${cache_root_2839}/nix-deps/lib:$LIBRARY_PATH
    __status=$?
    export PKG_CONFIG_PATH=${cache_root_2839}/nix-deps/lib/pkgconfig:${cache_root_2839}/nix-deps/share/pkgconfig:$PKG_CONFIG_PATH
    __status=$?
    ${venv_2840}/bin/pip install meson ninja
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix471_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2838}/nix && build_nix_inner__470_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix471_v0=''
        return "${__status}"
    fi
    mv "${source_root_2838}/nix/src/nix/nix" "${cache_root_2839}/nix-static"
    __status=$?
}

# darwin_export_sdk()
darwin_export_sdk__473_v0() {
    local command_81
    command_81="$(xcrun --show-sdk-path)"
    __status=$?
    local sdk_path_2776="${command_81}"
    dir_exists__38_v0 "${sdk_path_2776}"
    local ret_dir_exists38_v0__30_12="${ret_dir_exists38_v0}"
    if [ "$(( ! ret_dir_exists38_v0__30_12 ))" != 0 ]; then
        bail__177_v0 "The macOS SDK from Xcode or CommandLineTools is required to build Nix." 0
    fi
    local sdk_libs_2777="${sdk_path_2776}/usr/lib"
    local sdk_cflags_2778="-I${sdk_path_2776}/usr/include"
    env_var_set__119_v0 "LIBCURL_LIBS" "${sdk_libs_2777}"
    __status=$?
    env_var_set__119_v0 "LIBCURL_CFLAGS" "${sdk_cflags_2778}"
    __status=$?
    env_var_set__119_v0 "LIBARCHIVE_LIBS" "${sdk_libs_2777}"
    __status=$?
    env_var_set__119_v0 "LIBARCHIVE_CFLAGS" "${sdk_cflags_2778}"
    __status=$?
    env_var_set__119_v0 "OPENSSL_LIBS" "${sdk_libs_2777}"
    __status=$?
    env_var_set__119_v0 "OPENSSL_CFLAGS" "${sdk_cflags_2778}"
    __status=$?
    export LIBCURL_LIBS LIBCURL_CFLAGS                   LIBARCHIVE_LIBS LIBARCHIVE_CFLAGS                   OPENSSL_LIBS OPENSSL_CFLAGS
    __status=$?
}

# try_build_nix()
try_build_nix__474_v0() {
    get_cache_root__195_v0 
    local cache_root_2775="${ret_get_cache_root195_v0}"
    local array_82=("cc" "c++" "pkg-config" "make" "flex" "bison" "perl")
    check_deps__181_v0 array_82[@]
    __status=$?
    if [ "${__status}" != 0 ]; then
        bail__177_v0 "Missing required dependencies to build from source." 0
    fi
    get_osname__190_v0 
    local ret_get_osname190_v0__62_8="${ret_get_osname190_v0}"
    if [ "$([ "_${ret_get_osname190_v0__62_8}" != "_Darwin" ]; echo $?)" != 0 ]; then
        darwin_export_sdk__473_v0 
    fi
    get_source_root__392_v0 
    local ret_get_source_root392_v0__65_22="${ret_get_source_root392_v0}"
    dir_create__44_v0 "${ret_get_source_root392_v0__65_22}"
    __status=$?
    dir_create__44_v0 "${cache_root_2775}/nix-deps/lib/pkgconfig"
    __status=$?
    build_openssl__421_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix474_v0=''
        return "${__status}"
    fi
    build_boost__452_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix474_v0=''
        return "${__status}"
    fi
    build_nlohmann_json__441_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix474_v0=''
        return "${__status}"
    fi
    build_lowdown__432_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix474_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__460_v0 "libbrotlicommon" "c/include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix474_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__460_v0 "libsodium" "src/libsodium/include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix474_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__460_v0 "libeditline" "include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix474_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__460_v0 "libarchive" "libarchive"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix474_v0=''
        return "${__status}"
    fi
    build_nix__471_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix474_v0=''
        return "${__status}"
    fi
}

# is_nix_installed()
is_nix_installed__476_v0() {
    env_var_test__117_v0 "nosystem"
    local ret_env_var_test117_v0__26_8="${ret_env_var_test117_v0}"
    if [ "${ret_env_var_test117_v0__26_8}" != 0 ]; then
        ret_is_nix_installed476_v0=0
        return 0
    fi
    dir_exists__38_v0 "/nix/store"
    local ret_dir_exists38_v0__31_8="${ret_dir_exists38_v0}"
    if [ "${ret_dir_exists38_v0__31_8}" != 0 ]; then
        ret_is_nix_installed476_v0=1
        return 0
    fi
    ret_is_nix_installed476_v0=0
    return 0
}

# get_nix()
get_nix__477_v0() {
    get_cache_root__195_v0 
    local cache_root_2759="${ret_get_cache_root195_v0}"
    get_osname__190_v0 
    local osname_2760="${ret_get_osname190_v0}"
    get_system__192_v0 
    local system_2763="${ret_get_system192_v0}"
    local nix_path_2764="${cache_root_2759}/nix-static"
    local fakedir_path_2765="${cache_root_2759}/nix-deps/lib/libfakedir.dylib"
    enter_alt_buffer__171_v0 
    set_title__170_v0 "Building Nix..."
    trap "teardown__173_v0; exit 1" SIGKILL SIGTERM SIGINT SIGABRT
    __status=$?
    file_exists__39_v0 "${fakedir_path_2765}"
    local ret_file_exists39_v0__60_35="${ret_file_exists39_v0}"
    if [ "$(( $([ "_${osname_2760}" != "_Darwin" ]; echo $?) && $(( ! ret_file_exists39_v0__60_35 )) ))" != 0 ]; then
        dir_create__44_v0 "${cache_root_2759}/nix-deps/lib"
        __status=$?
        pull_binary__333_v0 "libfakedir.dylib" "${fakedir_path_2765}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            teardown__173_v0 1
            ret_get_nix477_v0=''
            return 1
        fi
    fi
    get_self__178_v0 
    local ret_get_self178_v0__69_62="${ret_get_self178_v0}"
    exists_newer__176_v0 "${fakedir_path_2765}" "${ret_get_self178_v0__69_62}"
    local ret_exists_newer176_v0__69_35="${ret_exists_newer176_v0}"
    if [ "$(( $([ "_${osname_2760}" != "_Darwin" ]; echo $?) && $(( ! ret_exists_newer176_v0__69_35 )) ))" != 0 ]; then
        pull_binary__333_v0 "libfakedir.dylib" "${fakedir_path_2765}"
        __status=$?
    fi
    file_exists__39_v0 "${nix_path_2764}"
    local ret_file_exists39_v0__73_8="${ret_file_exists39_v0}"
    if [ "${ret_file_exists39_v0__73_8}" != 0 ]; then
        teardown__173_v0 0
        ret_get_nix477_v0=0
        return 0
    fi
    env_var_test__117_v0 "nobins"
    local ret_env_var_test117_v0__78_8="${ret_env_var_test117_v0}"
    if [ "${ret_env_var_test117_v0__78_8}" != 0 ]; then
        try_build_nix__474_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            teardown__173_v0 1
            ret_get_nix477_v0=''
            return 1
        fi
    fi
    pull_binary__333_v0 "nix.${system_2763}" "${nix_path_2764}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        try_build_nix__474_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            teardown__173_v0 1
            ret_get_nix477_v0=''
            return 1
        fi
    fi
    chmod +x ${nix_path_2764}
    __status=$?
    teardown__173_v0 0
    ret_get_nix477_v0=0
    return 0
}

# migrate_nix_store()
migrate_nix_store__478_v0() {
    get_nix_root__194_v0 
    local ret_get_nix_root194_v0__107_36="${ret_get_nix_root194_v0}"
    local command_83
    command_83="$(readlink -f ${ret_get_nix_root194_v0__107_36})"
    __status=$?
    nix_root_2758="${command_83}"
    if [ "$(( __status != 0 ))" != 0 ]; then
        get_nix_root__194_v0 
        nix_root_2758="${ret_get_nix_root194_v0}"
    fi
    dir_exists__38_v0 "${nix_root_2758}/nix/store"
    local ret_dir_exists38_v0__112_12="${ret_dir_exists38_v0}"
    if [ "$(( ! ret_dir_exists38_v0__112_12 ))" != 0 ]; then
        ret_migrate_nix_store478_v0=0
        return 0
    fi
    >&2 echo "Migrating Nix store to system-wide install..."
    __status=$?
    nix --extra-experimental-features nix-command copy --from ${nix_root_2758} --all --no-check-sigs
    __status=$?
    if [ "$(( __status == 0 ))" != 0 ]; then
        chmod -R +wx ${nix_root_2758} && rm -rf ${nix_root_2758}
        __status=$?
    fi
}

# unpack_channels()
unpack_channels__479_v0() {
    get_repo_root__196_v0 
    local repo_root_2751="${ret_get_repo_root196_v0}"
    get_self__178_v0 
    local ret_get_self178_v0__128_52="${ret_get_self178_v0}"
    exists_newer__176_v0 "${repo_root_2751}/.nixie/channels" "${ret_get_self178_v0__128_52}"
    local ret_exists_newer176_v0__128_8="${ret_exists_newer176_v0}"
    if [ "${ret_exists_newer176_v0__128_8}" != 0 ]; then
        env_var_get__120_v0 "NIX_PATH"
        __status=$?
        local __NIX_PATH_2757="${ret_env_var_get120_v0}"
        env_var_set__119_v0 "NIX_PATH" "${repo_root_2751}/.nixie/channels:${__NIX_PATH_2757}"
        __status=$?
        export NIX_PATH
        __status=$?
        ret_unpack_channels479_v0=0
        return 0
    fi
    echo "Unpacking Nix channels, hang tight..."
    dir_create__44_v0 "${repo_root_2751}/.nixie"
    __status=$?
    untar__180_v0 "channels -C ${repo_root_2751}/.nixie" 0
    __status=$?
    if [ "${__status}" != 0 ]; then
        mkdir ${repo_root_2751}/.nixie/channels
        __status=$?
    fi
}

# populate_extras()
populate_extras__480_v0() {
    local args_2744=()
    get_nix_root__194_v0 
    local nix_root_2745="${ret_get_nix_root194_v0}"
    if [ "$([ "_${__EXTRA_FEATURES_36}" == "_" ]; echo $?)" != 0 ]; then
        args_2744+=("--extra-experimental-features" "${__EXTRA_FEATURES_36}")
    fi
    if [ "$([ "_${__EXTRA_SUBSTITUTERS_37}" == "_" ]; echo $?)" != 0 ]; then
        args_2744+=("--extra-substituters" "${__EXTRA_SUBSTITUTERS_37}")
    fi
    if [ "$([ "_${__EXTRA_TRUSTED_PUBLIC_KEYS_38}" == "_" ]; echo $?)" != 0 ]; then
        args_2744+=("--extra-trusted-public-keys" "${__EXTRA_TRUSTED_PUBLIC_KEYS_38}")
    fi
    get_osname__190_v0 
    local ret_get_osname190_v0__160_8="${ret_get_osname190_v0}"
    is_nix_installed__476_v0 
    local ret_is_nix_installed476_v0__160_41="${ret_is_nix_installed476_v0}"
    if [ "$(( $([ "_${ret_get_osname190_v0__160_8}" == "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed476_v0__160_41 )) ))" != 0 ]; then
        local command_89
        command_89="$(readlink -f ${nix_root_2745})"
        __status=$?
        args_2744+=("--store" "${command_89}")
    fi
    ret_populate_extras480_v0=("${args_2744[@]}")
    return 0
}

# launch_darwin_workaround(name: Text, nix_path: Text, args: [Text])
launch_darwin_workaround__481_v0() {
    local name_2857="${1}"
    local nix_path_2858="${2}"
    local args_2859=("${!3}")
    get_cache_root__195_v0 
    local cache_root_2860="${ret_get_cache_root195_v0}"
    get_nix_root__194_v0 
    local nix_root_2861="${ret_get_nix_root194_v0}"
    local fakedir_path_2862="${cache_root_2860}/nix-deps/lib/libfakedir.dylib"
    env_var_set__119_v0 "FAKEDIR_PATTERN" "/nix"
    __status=$?
    env_var_set__119_v0 "FAKEDIR_TARGET" "${nix_root_2861}/nix"
    __status=$?
    export FAKEDIR_PATTERN FAKEDIR_TARGET
    __status=$?
    _NIX_TEST_NO_SANDBOX=1             DYLD_INSERT_LIBRARIES="${fakedir_path_2862}"             DYLD_LIBRARY_PATH="${cache_root_2860}/nix-deps/lib"                 exec -a ${name_2857} "${nix_path_2858}" "${args_2859[@]}"
    __status=$?
}

# launch_shell_command(nix_path: Text, cmd: Text, extras: [Text], args: [Text])
launch_shell_command__482_v0() {
    local nix_path_2863="${1}"
    local cmd_2864="${2}"
    local extras_2865=("${!3}")
    local args_2866=("${!4}")
    get_repo_root__196_v0 
    local repo_root_2867="${ret_get_repo_root196_v0}"
    env_var_get__120_v0 "PWD"
    __status=$?
    local pwd_2868="${ret_env_var_get120_v0}"
    local name_2869="nix-shell"
    local shell_cmd_2870=("${repo_root_2867}/shell.nix" "--command" "${cmd_2864} ${args_2866[@]}")
    file_exists__39_v0 "${pwd_2868}/flake.nix"
    local ret_file_exists39_v0__209_8="${ret_file_exists39_v0}"
    if [ "${ret_file_exists39_v0__209_8}" != 0 ]; then
        name_2869="nix"
        local array_91=("develop" "${pwd_2868}" "-c" "${cmd_2864}")
        shell_cmd_2870=("${array_91[@]}" "${args_2866[@]}")
    else
        file_exists__39_v0 "${repo_root_2867}/flake.nix"
        local ret_file_exists39_v0__212_16="${ret_file_exists39_v0}"
        if [ "${ret_file_exists39_v0__212_16}" != 0 ]; then
            name_2869="nix"
            local array_93=("develop" "${repo_root_2867}" "-c" "${cmd_2864}")
            shell_cmd_2870=("${array_93[@]}" "${args_2866[@]}")
        else
            file_exists__39_v0 "${pwd_2868}/shell.nix"
            local ret_file_exists39_v0__215_16="${ret_file_exists39_v0}"
            if [ "${ret_file_exists39_v0__215_16}" != 0 ]; then
                shell_cmd_2870=("${pwd_2868}/shell.nix" "--command" "${cmd_2864} ${args_2866[@]}")
            fi
        fi
    fi
    get_osname__190_v0 
    local ret_get_osname190_v0__219_8="${ret_get_osname190_v0}"
    is_nix_installed__476_v0 
    local ret_is_nix_installed476_v0__219_41="${ret_is_nix_installed476_v0}"
    if [ "$(( $([ "_${ret_get_osname190_v0__219_8}" != "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed476_v0__219_41 )) ))" != 0 ]; then
        local array_add_96=("${extras_2865[@]}" "${shell_cmd_2870[@]}")
        launch_darwin_workaround__481_v0 "${name_2869}" "${nix_path_2863}" array_add_96[@]
    else
        exec -a ${name_2869} ${nix_path_2863} "${extras_2865[@]}" "${shell_cmd_2870[@]}"
        __status=$?
    fi
}

# launch_nix_shebang(nix_path: Text, file: Text, extras: [Text], args: [Text])
launch_nix_shebang__483_v0() {
    local nix_path_2846="${1}"
    local file_2847="${2}"
    local extras_2848=("${!3}")
    local args_2849=("${!4}")
    local shebang_2850=""
    i_2852=0;
    __AMBER_FIFO_97=$(mktemp -u) || exit 1
    mkfifo "$__AMBER_FIFO_97" || exit 1
    cat "${file_2847}" >"$__AMBER_FIFO_97" &
    __AMBER_PID_98=$!
    while IFS= read -r line_2851 || [ -n "$line_2851" ]; do
        if [ "$(( i_2852 == 1 ))" != 0 ]; then
            shebang_2850="${line_2851}"
            break
        fi
        (( i_2852++ )) || true
    done <"$__AMBER_FIFO_97"
    wait $__AMBER_PID_98
    rm -f "$__AMBER_FIFO_97"
    __status=$?
    starts_with__22_v0 "${shebang_2850}" "#"'!'""
    local ret_starts_with22_v0__246_12="${ret_starts_with22_v0}"
    if [ "$(( ! ret_starts_with22_v0__246_12 ))" != 0 ]; then
        ret_launch_nix_shebang483_v0=''
        return 0
    fi
    slice__24_v0 "${shebang_2850}" 2 0
    local ret_slice24_v0__248_27="${ret_slice24_v0}"
    split__4_v0 "${ret_slice24_v0__248_27}" " "
    local bang_args_2853=("${ret_split4_v0[@]}")
    array_shift__75_v0 "bang_args_2853"
    __status=$?
    local name_2854="${ret_array_shift75_v0}"
    i_2856=0;
    for arg_2855 in "${bang_args_2853[@]}"; do
        if [ "$([ "_${arg_2855}" != "_-i" ]; echo $?)" != 0 ]; then
            bang_args_2853["${i_2856}"]="--command"
            bang_args_2853["$(( i_2856 + 1 ))"]="${bang_args_2853[$(( i_2856 + 1 ))]?"Index out of bounds (at src/./nix.ab:255:42)"} ${file_2847} ${args_2849[@]}"
            break
        fi
        (( i_2856++ )) || true
    done
    get_osname__190_v0 
    local ret_get_osname190_v0__260_8="${ret_get_osname190_v0}"
    is_nix_installed__476_v0 
    local ret_is_nix_installed476_v0__260_41="${ret_is_nix_installed476_v0}"
    if [ "$(( $([ "_${ret_get_osname190_v0__260_8}" != "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed476_v0__260_41 )) ))" != 0 ]; then
        local array_add_101=("${extras_2848[@]}" "${bang_args_2853[@]}")
        launch_darwin_workaround__481_v0 "${name_2854}" "${nix_path_2846}" array_add_101[@]
    else
        exec -a ${name_2854} ${nix_path_2846} "${extras_2848[@]}" "${bang_args_2853[@]}"
        __status=$?
    fi
}

# launch_nix(self: Text, args: [Text])
launch_nix__484_v0() {
    local self_2739="${1}"
    local args_2740=("${!2}")
    get_cache_root__195_v0 
    local cache_root_2741="${ret_get_cache_root195_v0}"
    get_nix_root__194_v0 
    local nix_path_2743="${cache_root_2741}/nix-static"
    populate_extras__480_v0 
    local extras_2747=("${ret_populate_extras480_v0[@]}")
    split__4_v0 "${self_2739}" "/"
    local ret_split4_v0__277_33=("${ret_split4_v0[@]}")
    array_last__71_v0 ret_split4_v0__277_33[@]
    __status=$?
    local name_2750="${ret_array_last71_v0}"
    starts_with__22_v0 "${name_2750}" "nix-"
    local ret_starts_with22_v0__279_8="${ret_starts_with22_v0}"
    if [ "${ret_starts_with22_v0__279_8}" != 0 ]; then
        unpack_channels__479_v0 
    fi
    is_nix_installed__476_v0 
    local ret_is_nix_installed476_v0__282_8="${ret_is_nix_installed476_v0}"
    if [ "${ret_is_nix_installed476_v0__282_8}" != 0 ]; then
        migrate_nix_store__478_v0 
        nix_path_2743="nix"
    else
        get_nix__477_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            bail__177_v0 "Failed to obtain Nix. Check your internet connection." 0
        fi
    fi
    export NIX_SSL_CERT_FILE
    __status=$?
    file_exists__39_v0 "${args_2740[0]?"Index out of bounds (at src/./nix.ab:293:25)"}"
    local ret_file_exists39_v0__293_8="${ret_file_exists39_v0}"
    ends_with__23_v0 "${args_2740[0]?"Index out of bounds (at src/./nix.ab:293:52)"}" ".nix"
    local ret_ends_with23_v0__293_37="${ret_ends_with23_v0}"
    if [ "$(( ret_file_exists39_v0__293_8 && $(( ! ret_ends_with23_v0__293_37 )) ))" != 0 ]; then
        local args_shebang_2845=("${args_2740[@]}")
        array_shift__75_v0 "args_shebang_2845"
        __status=$?
        launch_nix_shebang__483_v0 "${nix_path_2743}" "${args_2740[0]?"Index out of bounds (at src/./nix.ab:296:43)"}" extras_2747[@] args_shebang_2845[@]
    fi
    starts_with__22_v0 "${name_2750}" "nix"
    local ret_starts_with22_v0__299_12="${ret_starts_with22_v0}"
    if [ "$(( ! ret_starts_with22_v0__299_12 ))" != 0 ]; then
        launch_shell_command__482_v0 "${nix_path_2743}" "${name_2750}" extras_2747[@] args_2740[@]
    fi
    get_osname__190_v0 
    local ret_get_osname190_v0__303_8="${ret_get_osname190_v0}"
    is_nix_installed__476_v0 
    local ret_is_nix_installed476_v0__303_41="${ret_is_nix_installed476_v0}"
    if [ "$(( $([ "_${ret_get_osname190_v0__303_8}" != "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed476_v0__303_41 )) ))" != 0 ]; then
        local array_add_102=("${extras_2747[@]}" "${args_2740[@]}")
        launch_darwin_workaround__481_v0 "${name_2750}" "${nix_path_2743}" array_add_102[@]
    else
        exec -a ${name_2750} ${nix_path_2743} "${extras_2747[@]}" "${args_2740[@]}"
        __status=$?
    fi
}

array_104=("tar" "gzip" "uname")
check_deps__181_v0 array_104[@]
__status=$?
if [ "${__status}" != 0 ]; then
    exit 1
fi
typeset -r cmdl_88=("$0" "$@")
args_0=("${cmdl_88[@]}")
load_features__212_v0 
__status=$?
if [ "${__status}" != 0 ]; then
    bail__177_v0 "The environment file in the resource archive is incomplete." 1
fi
catch_args__221_v0 "args_0"
array_shift__75_v0 "args_0"
__status=$?
self_297="${ret_array_shift75_v0}"
file_exists__39_v0 "/etc/pki/tls/certs/ca-bundle.crt"
ret_file_exists39_v0__33_5="${ret_file_exists39_v0}"
get_osname__190_v0 
ret_get_osname190_v0__35_5="${ret_get_osname190_v0}"
if [ "${ret_file_exists39_v0__33_5}" != 0 ]; then
    env_var_set__119_v0 "NIX_SSL_CERT_FILE" "/etc/pki/tls/certs/ca-bundle.crt"
    __status=$?
elif [ "$([ "_${ret_get_osname190_v0__35_5}" != "_Darwin" ]; echo $?)" != 0 ]; then
    env_var_set__119_v0 "NIX_SSL_CERT_FILE" "/etc/ssl/cert.pem"
    __status=$?
fi
launch_nix__484_v0 "${self_297}" args_0[@]
exit 0
cat <<DONOTPARSE

-----BEGIN ARCHIVE SECTION-----[?1049h
‹Œ!jÿ íÎOo‚0pÎ|
ã]ÓŠ< vY³E(ÆH‰ü·}ú¡ffÙ}K–=¿ËÛ¼}Ş·U©Üíë´Ñ~i-ëR[ß+1móv¾öí¥Z‡h¿`ßìdİ>©ıOl)|7ºc®}Œ»UqêÅ›õZVIG½Ê2mºú5„“@p
æ·¹Ï®ğÃ@°iôN¹=°çËe0}Eëİ³ëÒc-·ıXÆyqêoêì™2Ÿ/\Áç³q.ó÷7jVtõRTÊÎrµM•ÑæÇ‘ãè3¾Œ&||R[b–EBs”¬*Û†3(ÕŠX‡C’‘Ò:q-Ú_Ÿã1†}bö$Õ5                 €¿ìt'üï (  [?1049l [2K[37;2m# (tarball data)[0m