from rich.console import Console
from logging      import debug, error

from ...output    import script
from ..           import common, fetchers

def _open_default_paths() -> script.NixieScript:
    common.goto_git_root()
    try:
        debug("Trying ./nix")
        return script.NixieScript('./nix')
    except:
        try:
            debug("Trying ./nix-shell")
            return script.NixieScript('./nix-shell')
        except:
            error("No nix script found in this repository. Run 'nixie init' to generate one.")
            exit(1)

def _cmd(console: Console, **args):
    ns: script.NixieScript
    newchns = dict()

    tdir = common.mktmp()

    with console.status("Retrieving Nix channels...", spinner='earth') as st:
        newchns = common.channels_from_args(args, st)
    with console.status("Fetching latest resources...", spinner='earth') as st:
        srcs_eval, bins_eval = fetchers.eval_latest_sources(args)

    with console.status("Reading Nix script configuration...", spinner='dots12') as st:
        if args['script'] is not None:
            try:
                ns = script.NixieScript(args['script'])
            except FileNotFoundError:
                error(f"'{args['script']}': No such file or directory.")
                exit(1)
            except Exception:
                error(f"'{args['script']}' does not appear to be a valid script generated by Nixie.")
                exit(1)
        else:
            ns = _open_default_paths()

    debug(ns.features.print_features())
    if ns.features.include_sources:
        debug("This script includes sources.")
    if ns.features.include_bins:
        debug("This script includes binaries.")
    debug("Included channels: %s" %list(ns.features.pinned_channels.keys()))
    ns.features = common.features_from_args(args, ns.features)

    ns.features.sources_drv = srcs_eval
    ns.features.bins_drv = bins_eval

    with console.status("Downloading offline binaries...", spinner="earth") as st:
        fetchers.prefetch_resources(ns.features.source_cache, tdir, bins_eval, srcs_eval, args, st)

    #TODO: perform nixpkgs version check
    if len(newchns) > 0:
        ns.features.pinned_channels.update(newchns)

    with console.status("Updating Nix script...", spinner='dots12') as st:
        with open(ns.fname, mode='wb') as fi:
            ns.build(fi)
